"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var temperatureConverter_1 = require("./temperatureConverter");
var distanceConverter_1 = require("./distanceConverter");
var numberUtils_1 = require("./numberUtils");
var stringManipulator_1 = require("./stringManipulator");
var palindromeChecker_1 = require("./palindromeChecker");
console.log("===================Task 1=================");
console.log("Input: 100. Result: ".concat((0, temperatureConverter_1.fahrenheitToCelsius)(100)));
console.log("===================Task 1=================");
console.log("===================Task 2=================");
console.log("Input: 100000. Result: ".concat((0, distanceConverter_1.centiToKm)(100000), " km"));
console.log("===================Task 2=================");
console.log("===================Task 3=================");
console.log("Input: 100. Result: ".concat((0, numberUtils_1.isOdd)(100)));
console.log("Input: 101. Result: ".concat((0, numberUtils_1.isOdd)(101)));
console.log("===================Task 3=================");
console.log("===================Task 4=================");
console.log("Input: \"Hello World Hello\". Result: ".concat((0, stringManipulator_1.removeFirstOccurrence)("Hello World Hello", "Hello")));
console.log("Input: \"Test Test\". Result: ".concat((0, stringManipulator_1.removeFirstOccurrence)("Test Test", "Test")));
console.log("===================Task 4=================");
console.log("===================Task 5=================");
console.log("Input: \"abcba\". Result: ".concat((0, palindromeChecker_1.isPalindrome)("abcba")));
console.log("Input: \"12321\". Result: ".concat((0, palindromeChecker_1.isPalindrome)("12321")));
console.log("===================Task 5=================");
