"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var task1_1 = require("./task1");
var task2_1 = require("./task2");
var task3_1 = require("./task3");
var task4_1 = require("./task4");
var task5_1 = require("./task5");
console.log("===================Task 1=================");
console.log("Input: 100. Result: ".concat((0, task1_1.fahrenheitToCelsius)(100)));
console.log("===================Task 1=================");
console.log("===================Task 2=================");
console.log("Input: 100000. Result: ".concat((0, task2_1.centiToKm)(100000), " km"));
console.log("===================Task 2=================");
console.log("===================Task 3=================");
console.log("Input: 100. Result: ".concat((0, task3_1.isOdd)(100)));
console.log("Input: 101. Result: ".concat((0, task3_1.isOdd)(101)));
console.log("===================Task 3=================");
console.log("===================Task 4=================");
console.log("Input: \"Hello World Hello\". Result: ".concat((0, task4_1.removeFirstOccurrence)("Hello World Hello", "Hello")));
console.log("Input: \"Test Test\". Result: ".concat((0, task4_1.removeFirstOccurrence)("Test Test", "Test")));
console.log("===================Task 4=================");
console.log("===================Task 5=================");
console.log("Input: \"abcba\". Result: ".concat((0, task5_1.isPalindrome)("abcba")));
console.log("Input: \"12321\". Result: ".concat((0, task5_1.isPalindrome)("12321")));
console.log("===================Task 5=================");
