"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var rectangleCalculator_1 = require("./rectangleCalculator");
var circleCalculator_1 = require("./circleCalculator");
var triangleCalculator_1 = require("./triangleCalculator");
var dateCalculator_1 = require("./dateCalculator");
var stringFormatter_1 = require("./stringFormatter");
console.log("Area of rectangle: ".concat((0, rectangleCalculator_1.calculateRectangleArea)(5, 3)));
console.log("Circle properties for radius 5:", (0, circleCalculator_1.calculateCircle)(5));
console.log("The third angle in the triangle is: ".concat((0, triangleCalculator_1.findAngleOfTriangle)(80, 65)));
console.log("Difference in days between the dates: ".concat((0, dateCalculator_1.getDiffInDays)(new Date("2021-01-01"), new Date("2021-01-10"))));
console.log("Initials of the name: ".concat((0, stringFormatter_1.getInitials)("Zulfikar Ditya")));
